### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/usr/share/jupyter'

### ISSUE THREAD

**Issue by axjtan** [RoboStack/jupyter-ros#10]
Hi I tried to run the following:
`jupyter nbextension install --py --symlink --sys-prefix jupyros`

but ended up getting this error instead.

> OSError: [Errno 13] Permission denied: '/usr/share/jupyter'

**Comment by wolfv** [comment]
you might have to run this command with `sudo` since it's trying to write something in `/usr/share/jupyter`.
