### ISSUE TITLE
[feature request] support bag files

### ISSUE THREAD

**Issue by flixr** [RoboStack/jupyter-ros#13]
This looks really promising!

However instead of accepting live data, IMHO a more common use case for jupyter is to analyze recorded data. So in the ROS context that usually means bag files.

It would be great to have good support for bag files.

https://github.com/cruise-automation/webviz could be useful here as well.

**Comment by wolfv** [comment]
Thanks for the suggestion! Indeed, a bag player of some sort would be very useful, and probably not too hard to implement. If you are willing to give it a go, I can help you out! 

The easiest would be to write it in python, and hook up some `ipywidget` Buttons to start/stop the playback, and then run the playback in a background python thead.

**Comment by HemaZ** [comment]
I will work on this feature. @wolfv could you please assign it to me?
Thank you.

**Comment by wolfv** [comment]
@HemaZ That's awesome. Can't seem to be able to assign you from the button (did you disable that feature?).

Anyways, let me know how it goes. I am happy to help out with this.

**Comment by HemaZ** [comment]
@wolfv just opened the PR. please check it, and feel free to ask for any modifications. 
i don't know if this is the best approach to implement it. but it works :D
![Screenshot-20190415214614-1073x524](https://user-images.githubusercontent.com/6087928/56162175-a3a4d800-5fcb-11e9-9460-d8e180919d7c.png)

**Comment by wolfv** [comment]
Initial bag file support has been merged!
