### ISSUE TITLE
error with "jupyter nbextension install --py --symlink --sys-prefix jupyros"

### ISSUE THREAD

**Issue by ruomingzhai** [RoboStack/jupyter-ros#144]
when I run "jupyter nbextension install --py --symlink --sys-prefix jupyros" , it breaks down for the following error. My environment is python 3.9 and it seems python3.x do not support the Unicode function. Hope to get some clues!!!!
```
 File "/jupyter-ros/jupyros/ros1/ros3d.py", line 73, in ROSConnection
    url = Unicode(os.environ.get("JUPYROS_WEBSOCKET_URL", "ws://Z9d2n4:9090")).tag(sync=True)
NameError: name 'Unicode' is not defined
```

**Comment by Andor233** [comment]
Same question here
