### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pitosalas** [RoboStack/jupyter-ros#18]
I think I have it almost installed except this...
<img width="1143" alt="Screen Shot 2019-06-24 at 10 46 49 PM" src="https://user-images.githubusercontent.com/44681/60065485-01dbee80-96d2-11e9-9da6-c630aa5c361b.png">

**Comment by wolfv** [comment]
can you check that the regular ipywidgets work fine?

e.g. execute:

```
from ipywidgets import Button
Button()
```

**Comment by Timple** [comment]
Same problem here. Solved it like this:

```
pip install ipywidgets
jupyter nbextension enable --py widgetsnbextension
```

Perhaps add this to the installation manual? Not everybody was using widgets before jupyros :)

**Comment by wolfv** [comment]
PR welcome! :)

**Comment by pitosalas** [comment]
THANKS! It worked. What a cool tool :)
