### ISSUE TITLE
jupyter lab supported?

### ISSUE THREAD

**Issue by pitosalas** [RoboStack/jupyter-ros#25]
I am trying to get the package to work with Jupyter Lab. However the UI widget just for pub and subscribe don't seem to work. Do I install them differently for lab?

**Comment by wolfv** [comment]
you need to install the ipywidgets package for jupyterlab. 

`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

**Comment by pitosalas** [comment]
Other than the cooler "lab" UI are there things you can do there that you can't do in a notebook? (e.g. sidecar whatever that is?)

Because: "ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website."

**Comment by EricCousineau-TRI** [comment]
FWIW: https://discourse.ros.org/t/jupyterlab-the-cloud-robotics-command-station/15859
