### ISSUE TITLE
Available ranges for jr.publish

### ISSUE THREAD

**Issue by pitosalas** [RoboStack/jupyter-ros#28]
I dont know how you determine the ranges for the generated ui for jr.publish. But if you are publishing Twist, the ranges are 0.0 -> I think 100 or something. It would be nice if you changed that to -10 -> +10. When the max is 100 the slider is too sensitive for normal cases.

**Comment by wolfv** [comment]
Hi @pitosalas and @HemaZ I finally fixed this for the moment by changing to a Int Text field, and Float text field. I think that's more appropriate.
