### ISSUE TITLE
'widget_for_msg' does not exist

### ISSUE THREAD

**Issue by ifollowbenoit** [RoboStack/jupyter-ros#3]
Hello,

I got this error while tring to create my widget with your example. I checked the source code and the widget_for_msg function doesn't seem to exist. Also could you give me an example of the use of the jupyros.add_widgets function ? 
Thank you very much

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-fbd18e5f7356> in <module>()
----> 1 jupyros.widget_for_msg()

AttributeError: module 'jupyros' has no attribute 'widget_for_msg'

**Comment by wolfv** [comment]
Hi @ifollowbenoit 

thanks for opening the issue. 

That function was renamed to `jupyros.publish(topic, msg_type)`

You can find them all here: https://github.com/RoboStack/jupyter-ros/blob/master/jupyros/ros_widgets.py
And for the subscriber: https://github.com/RoboStack/jupyter-ros/blob/master/jupyros/pubsub.py

Also note that the `latch` and `rate` button/input do not work yet. 

I'll try to update the repo soon with a better Readme.

**Comment by wolfv** [comment]
hey, I updated the readme image to reflect the new function names.

**Comment by ifollowbenoit** [comment]
Thank you very much @wolfv
