### ISSUE TITLE
Custom ROS Messages import from ROS MODULE in CATKIN workspace

### ISSUE THREAD

**Issue by rikobrandes** [RoboStack/jupyter-ros#32]
I would like to import custom ROS message types definitions from another ROS module lying in the same catkin workspace as the jupyter notebook. Anyone knows how to do that? 

Actually it would be great to run the jupyter-ros notebook as catkin module, to realize a live monitoring node of the stack. Any ideas? 

Thanks a lot. 

Riko

**Comment by rikobrandes** [comment]
Solved. My script that sourced the catkin_ws had an error.

**Comment by wolfv** [comment]
awesome!

**Comment by koksyuen** [comment]
So, how do you actually solve it? Because I'm still unable to import my ROS custom message in Jupyter Notebook
How do you source catkin_ws within that Jupyter Notebook (ipynb)?

**Comment by wolfv** [comment]
I think you need to modify the `PYTHONPATH` or run the kernel generator to create a custom kernel that sets these values properly (there is a little bit of docs here: https://jupyter-ros.readthedocs.io/en/latest/installation.html)
