### ISSUE TITLE
Did anybody try to install this in Docker?

### ISSUE THREAD

**Issue by rubenanapu** [RoboStack/jupyter-ros#38]
Hi all,

I tried installing `jupyter-ros` in docker `ubunut:16.04`, later in `osrf/ros:kinetic-desktop-full`, but it always fails with different errors.

Did anybody manage to install it on Docker?

**Comment by rubenanapu** [comment]
Well, the problem was because I was trying to run the commands in a Docker Container, but using a `Dockerfile` to create an image seems to work.

That is the reason why I closed the issue.

**Comment by wolfv** [comment]
great! Happy that you resolved the issue.

**Comment by psychemedia** [comment]
@rubenanapu Have you posted the Dockerfile / setup anywhere? I'd quite like to give this extension a spin but I'm not really familiar with setting ROS environments up.
