### ISSUE TITLE
Publishing rate from Jupyter is not correct.

### ISSUE THREAD

**Issue by mhaboali** [RoboStack/jupyter-ros#45]
Hi,

When I tried to publish string message using Start button with rate = 10, I noticed from the terminal when I ran rostopic hz the frequency was increasing constantly with low increases from 0.1 hz to 9.8 hz.

How can I avoid this issue?

**Comment by wolfv** [comment]
Hi @mhaboali 

I just checked this -- indeed there was a small error from using a `rospy.sleep(...)` instead of using 

```
r = rospy.Rate(X)
r.sleep()
```

which gives a more accurate timeout. 

However, I couldn't see a big deviation as you do. I have a PR to make this function behave better.

**Comment by wolfv** [comment]
Fixed, thanks again for the bug report!
