### ISSUE TITLE
NameError: global name 'Error' is not defined

### ISSUE THREAD

**Issue by LoyVanBeek** [RoboStack/jupyter-ros#5]
When re-subscribing to a topic when you re-execute the cell (which you shouldn't, I know :-) ), I get this error. 
I could make a PR but I'm not sure what it should be :man_shrugging: Maybe RuntimeError? 

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-a297a3eee99c> in <module>()
----> 1 jr.subscribe('/barcode', String, cb)

/home/lvb/.local/lib/python2.7/site-packages/jupyros/pubsub.pyc in subscribe(topic, msg_type, callback)
     48 
     49     if subscriber_registry.get(topic):
---> 50         raise Error("Already registerd...")
     51 
     52     out = widgets.Output(layout={'border': '1px solid gray'})

NameError: global name 'Error' is not defined
```

Version info: 

The version of the notebook server is: 5.7.8
```
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
```

**Comment by wolfv** [comment]
To be honest, this is one of the rough edges. Currently there can be only one subscriber widget per session per topic ... 
Upon destruction of a subscriber widget, we should "stop" the subscriber thread (as done when pressing the stop button) and then allow registering a new subscriber. 

I think there might be a comm close event from the widget, we need to check that.

**Comment by martinRenou** [comment]
I think what @LoyVanBeek means is that it should not be `NameError: global name 'Error' is not defined` but `RuntimeError: Already registered...`

**Comment by martinRenou** [comment]
Concerning what you are saying @wolfv I think there is a `close` method that you can reimplement :)

**Comment by LoyVanBeek** [comment]
> I think what @LoyVanBeek means is that it should not be NameError: global name 'Error' is not defined but RuntimeError: Already registered...

Exactly, I knew i was doing something 'wrong' when re-subscribing, but the exception `Error` that should be raised does not exist in that context. Perhaps is should be `RuntimeError` but I'm not sure: https://github.com/RoboStack/jupyter-ros/pull/6

**Comment by wolfv** [comment]
thanks for the PR!

**Comment by LoyVanBeek** [comment]
Those 7 characters were the easiest PR is a while. Thnx for making this!
