### ISSUE TITLE
default install raises error

### ISSUE THREAD

**Issue by Bazmundi** [RoboStack/jupyter-ros#64]
From https://github.com/RoboStack/jupyter-ros

typed in

```
pip install jupyter bqplot pyyaml ipywidgets
jupyter nbextension enable --py --sys-prefix ipywidgets
```
Results in:
```
KeyError: 'The Python module ipywidgets is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'

```

Happens both on Windoze 10 install and Debian 10 install.

**Comment by Bazmundi** [comment]
Going to: https://ipywidgets.readthedocs.io/en/latest/user_install.html

It appears the correct installation is:

```
pip install ipywidgets
jupyter nbextension enable --py widgetsnbextension
```

And where installing under venv the following option may be required:

```
jupyter nbextension enable --py widgetsnbextension --sys-prefix
```

**Comment by Tobias-Fischer** [comment]
Readme was updated since.
