### ISSUE TITLE
Lab 3 Update

### ISSUE THREAD

**Issue by hbcarlos** [RoboStack/jupyter-ros#69]
- Upgrade script: https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#upgrading-library-versions-using-the-upgrade-script

**Comment by wolfv** [comment]
thanks!

**Comment by hbcarlos** [comment]
Probably related to https://github.com/RoboStack/jupyterlab-ros/issues/23

**Comment by Tobias-Fischer** [comment]
This was fixed previously.
