### ISSUE TITLE
Distribution on conda-forge

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/jupyter-ros#72]
Hi @hbcarlos @wolfv - are you happy for me to put jupyter-ros (and jupyterlab-ros) on conda-forge? This will make installation significantly easier, especially in conjunction with ros-noetic.

**Comment by wolfv** [comment]
Hey @Tobias-Fischer actually we already put packages for Jupyterlab-ROS and Jupyter-ROS on the Robostack channel (they were built by hand, by me...)

The nice thing about that is that it allowed us to depend on the pieces of ROS that are necessary to smoothly get started with those two packages.

I wonder if we can put it on conda-forge and add RoboStack as a required channel for those packages ... I think there is an entry in teh conda-forge yaml config or something.

**Comment by wolfv** [comment]
Also, jlab-ros and jupyter-ros are noarch packages currently (IIRC). 

I think we can't properly handle them in additional recipes just yet. We should only build noarch recipes on Linux :) I think we can add some simple logic so we could add those two packages to the robostack noetic repo.

**Comment by Tobias-Fischer** [comment]
Seeing that those packages are already in the robostack channel, I think we can close this.
